plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'
    - 'config/application.rb'
    - 'spec/**/*'
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'spec/**/*'