FROM ruby:3.3-bullseye

RUN apt-get update -qq && apt-get install -y \
    nodejs \
    postgresql-client \
    libyaml-dev \
    build-essential \
    libpq-dev

# RAILS_ENVを明示的に指定
ENV RAILS_ENV=development
ENV NODE_ENV=development

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]