version: "3.9"
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      # - DATABASE_URL=postgresql://postgres:password@db:5432/fighters_record_api_development
      - RAILS_ENV=development
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  db_data: