FROM ruby:3.3

RUN apt-get update -qq && apt-get install -y \
    nodejs \
    postgresql-client \
    libyaml-dev \
    build-essential \
    libpq-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
